# Generated by Django 4.2.18 on 2025-02-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='object_id',
        ),
    ]
